<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Pradnya-Nandrekar" failures="1" tests="3" name="ECommerce_TestCases.TestCase08" time="80.468" errors="0" timestamp="2024-12-24T18:47:37 IST" skipped="2">
  <testcase classname="ECommerce_TestCases.TestCase08" name="Sorting_Product_ByPrice_HtoL" time="80.468">
    <failure message="Sort By- price High-Low Failed..: lists don&#039;t have the same size expected [68] but found [110]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Sort By- price High-Low Failed..: lists don't have the same size expected [68] but found [110]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:907)
at org.testng.Assert.assertEquals(Assert.java:1089)
at ECommerce_TestCases.TestCase08.Sorting_Product_ByPrice_HtoL(TestCase08.java:89)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </failure>
  </testcase> <!-- Sorting_Product_ByPrice_HtoL -->
  <system-out>
    <![CDATA[Test Started
TestCase Failed]]>
  </system-out>
  <testcase classname="ECommerce_TestCases.TestCase08" name="Sorting_Product_ByPrice_LtoH">
    <skipped/>
  </testcase> <!-- Sorting_Product_ByPrice_LtoH -->
  <system-out/>
  <testcase classname="ECommerce_TestCases.TestCase08" name="Sorting_Product_rating">
    <skipped/>
  </testcase> <!-- Sorting_Product_rating -->
  <system-out/>
</testsuite> <!-- ECommerce_TestCases.TestCase08 -->
