<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Pradnya-Nandrekar" failures="2" tests="3" name="ECommerce_TestCases.TestCase08_trial" time="36.860" errors="0" timestamp="2024-12-11T18:05:27 IST" skipped="1">
  <testcase classname="ECommerce_TestCases.TestCase08_trial" name="Sorting_Product_ByPrice_HtoL" time="23.513">
    <failure message="Price Sorting H to L failed expected [0] but found [2]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Price Sorting H to L failed expected [0] but found [2]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at ECommerce_TestCases.TestCase08_trial.Sorting_Product_ByPrice_HtoL(TestCase08_trial.java:83)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </failure>
    <system-out>
      <![CDATA[Test Started
TestCase Failed]]>
    </system-out>
  </testcase> <!-- Sorting_Product_ByPrice_HtoL -->
  <testcase classname="ECommerce_TestCases.TestCase08_trial" name="Sorting_Product_ByPrice_LtoH" time="13.347">
    <failure message="Price Sorting L to H failed expected [0] but found [3]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: Price Sorting L to H failed expected [0] but found [3]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at ECommerce_TestCases.TestCase08_trial.Sorting_Product_ByPrice_LtoH(TestCase08_trial.java:52)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </failure>
    <system-out>
      <![CDATA[Test Started
TestCase Failed]]>
    </system-out>
  </testcase> <!-- Sorting_Product_ByPrice_LtoH -->
  <testcase classname="ECommerce_TestCases.TestCase08_trial" name="Sorting_Product_rating">
    <skipped/>
  </testcase> <!-- Sorting_Product_rating -->
  <system-out>
    <![CDATA[Test Started
Test Started
TestCase Failed
Test Started
TestCase Failed
Test Started
TestCase Failed
Test Started
Logged In Successfully
Test Passed successfuly
Test Started
There was a problem
Your password is incorrect
Test Passed successfuly
Test Started
Incorrect phone number
We cannot find an account with that mobile number
Test Passed successfuly
Test Started
Test Passed successfuly
Test Started
Test Passed successfuly
Test Started
----------- Filter By Brand Test Pass -----------
Test Started
----------- Filter By Brand Test Pass -----------
TestCase Failed
Test Started
All Product Details are present
Test Passed successfuly
Test Started
Test Passed successfuly
Test Started
Test Started
Test Passed successfuly
Test Started
Test Passed successfuly
Test Started
Test Passed successfuly
Test Started
Test Passed successfuly
Test Started
Test Passed successfuly
Test Started
Test Passed successfuly]]>
  </system-out>
</testsuite> <!-- ECommerce_TestCases.TestCase08_trial -->
