<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Pradnya-Nandrekar" failures="1" tests="3" name="ECommerce_TestCases.TestCase06" time="35.321" errors="0" timestamp="2024-12-06T23:37:30 IST" skipped="2">
  <testcase classname="ECommerce_TestCases.TestCase06" name="searching_Wt_Filters" time="17.426">
    <failure message="filtered product list has wrong discount product expected [0] but found [5]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: filtered product list has wrong discount product expected [0] but found [5]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at ECommerce_TestCases.TestCase06.searching_Wt_Filters(TestCase06.java:53)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:248)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:62)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1570)
]]>
    </failure>
    <system-out>
      <![CDATA[Test Started
----------- Filter By Brand Test Pass -----------]]>
    </system-out>
  </testcase> <!-- searching_Wt_Filters -->
  <testcase classname="ECommerce_TestCases.TestCase06" name="searching_Wt_Filters" time="17.895">
    <skipped/>
    <system-out>
      <![CDATA[Test Started
----------- Filter By Brand Test Pass -----------]]>
    </system-out>
  </testcase> <!-- searching_Wt_Filters -->
  <testcase classname="ECommerce_TestCases.TestCase06" name="searching_Wt_Price">
    <skipped/>
  </testcase> <!-- searching_Wt_Price -->
  <system-out>
    <![CDATA[Test Started
Test Started
Test Started
Logged In Successfully
Test Passed successfuly
Test Started
There was a problem
Your password is incorrect
Test Passed successfuly
Test Started
Incorrect phone number
We cannot find an account with that mobile number
Test Passed successfuly
Test Started
Test Passed successfuly
Test Started
Test Passed successfuly
Test Started
----------- Filter By Brand Test Pass -----------
Test Started
----------- Filter By Brand Test Pass -----------
Test Started
All Product Details are present
Test Passed successfuly
Test Started
Test Started
Test Passed successfuly
Test Started
Test Passed successfuly
Test Started
Test Started
Test Passed successfuly
Test Started
Test Passed successfuly
Test Started
Test Started
Test Started
Test Passed successfuly]]>
  </system-out>
</testsuite> <!-- ECommerce_TestCases.TestCase06 -->
